default: &default
  ASSET_HOST: 'localhost:3000'
  APPLICATION_HOST: 'localhost:3000'
  PORT: '3000'
  RACK_ENV: 'development'
  RACK_MINI_PROFILER: '0'
  REDISTOGO_URL: 'redis://localhost'
  SECRET_KEY_BASE: 'development_secret'
  EXECJS_RUNTIME: 'Node'
  SMTP_ADDRESS: ''
  SMTP_DOMAIN: ''
  SMTP_PASSWORD: ''
  SMTP_USERNAME: ''
  WEB_CONCURRENCY: 1

development:
  <<: *default

test:
  <<: *default
